# syntax: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Browser

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Browser

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        run: |
          rm -f package.json
          rm -f package-lock.json
          npm init -y
          npm i -D rimraf typescript puppeteer
          npm i -D webpack webpack-cli ts-loader nyc coverage-istanbul-loader

      - name: Determine default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_ENV
          echo "default_branch_ref=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ env.default_branch }}

      - name: Deploy
        if: github.ref == env.default_branch_ref
        run: echo "Run!"

      - name: Prepare
        run: |
          node_modules/.bin/rimraf .nyc_output coverage
          node_modules/.bin/webpack -c webpack/webpack.bundle.instrumented.js
          node_modules/.bin/tsc -p scripts/browserTest/tsconfig.json

      - name: Test
        run: |
          node scripts/browserTest/index.mjs --coverage

      - name: Coverage
        run: |
          node_modules/.bin/nyc report --exclude "src/{bundles,htm,ui}/**" --reporter=text --reporter=html --reporter=lcov

      - name: Upload coverage to Codecov
        if: github.ref == env.default_branch_ref
        uses: codecov/codecov-action@v2
