name: Deno

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - 'bundles/**'
      - 'deno_lib/**'
      - 'dev/**'
      - 'readme/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'bundles/**'
      - 'deno_lib/**'
      - 'dev/**'
      - 'readme/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ['v1.x']
        node-version: ['14.x']

    name: Deno ${{ matrix.deno }} sample

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # install node to run denoify.land
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # install deno to run the test
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Denoify
        run: npm run denoify

      - name: Run Tests
        run: |
          deno --version
          deno test --no-check -c tsconfig.deno.json deno.test.tsx deno.test2.tsx
